daemonize = no
fail = no
exit-idle-time = -1
allow-exit = no
high-priority = yes
nice-level = -11
realtime-scheduling = no
default-sample-format = s16le
default-sample-rate = 44100
alternate-sample-rate = 48000
default-sample-channels = 2
default-channel-map = front-left,front-right
flat-volumes = no
rescue-streams = yes
